import Head from "next/head";
import { Stack, Typography } from "@mui/material";
import NavBar from "../components/navBar";
import AboutMe from "../components/aboutMe";
import Intro from "../components/intro";
import TableExperience from "../components/tableExperience";
import Projets from "../components/Projet";
import Contact from "../components/Contact";
import EasterEgg from "../components/EasterEgg";
import FinalEasterEgg from "../components/FinalEasterEgg";
import LineRight from "../components/LineRight";
import LineLeft from "../components/LineLeft";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nowak Louis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Stack
        sx={{
          minHeight: "100vh",
          padding: "1rem",
          backgroundColor: "#013328",
          backgroundSize: "cover",
          backgroundAttachment: "fixed",
        }}
      >
        <NavBar />
        <Intro />
        <AboutMe />
        <TableExperience />
        <FinalEasterEgg />
        <Projets />
        <Contact />
        <EasterEgg />
        <LineLeft />
        <LineRight />
      </Stack>
    </>
  );
}
